services:
    backend:
        build:
            context: .
            dockerfile: apps/backend/Dockerfile
        ports:
            - '5000:5000'
            - '5080:5080'
        environment:
            PORT: 5000
            WS_PORT: 5080
            CORS_ORIGIN: http://localhost:3000
    web:
        build:
            context: .
            dockerfile: apps/web/Dockerfile
        ports:
            - '3000:3000'
        environment:
            NEXT_PUBLIC_API_URL: http://localhost:5000
            NEXT_PUBLIC_WS_URL: ws://localhost:5080
